title: 
email: hengzhihe@g.ucla.edu
description: "Hengzhi He"
baseurl: "" # 基础URL，如果您的网站不在子路径上则留空
url: "https://hehz2020.github.io" # 您的网站URL

# 社交媒体用户名（如果您不想添加，可以留空或删除这些行）
twitter_username: 
github_username:  

theme: minima
